// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-x6OJ-8SzSzMEAWE2nVl8PxRGysgtVgc',
    appId: '1:614646448256:web:f8cdcb14cca2abaa1c6665',
    messagingSenderId: '614646448256',
    projectId: 'chattesting-8a506',
    authDomain: 'chattesting-8a506.firebaseapp.com',
    storageBucket: 'chattesting-8a506.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTzX1TSmXGUSdsDhmmtCYHKXniSOjYAk',
    appId: '1:614646448256:android:cb0bb9703e0ffe5a1c6665',
    messagingSenderId: '614646448256',
    projectId: 'chattesting-8a506',
    storageBucket: 'chattesting-8a506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57yNdLqsb2lOXiU6uWiRL-CP75mCi1s8',
    appId: '1:614646448256:ios:8898dcbd6070d80b1c6665',
    messagingSenderId: '614646448256',
    projectId: 'chattesting-8a506',
    storageBucket: 'chattesting-8a506.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57yNdLqsb2lOXiU6uWiRL-CP75mCi1s8',
    appId: '1:614646448256:ios:8898dcbd6070d80b1c6665',
    messagingSenderId: '614646448256',
    projectId: 'chattesting-8a506',
    storageBucket: 'chattesting-8a506.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-x6OJ-8SzSzMEAWE2nVl8PxRGysgtVgc',
    appId: '1:614646448256:web:4548a618616880631c6665',
    messagingSenderId: '614646448256',
    projectId: 'chattesting-8a506',
    authDomain: 'chattesting-8a506.firebaseapp.com',
    storageBucket: 'chattesting-8a506.appspot.com',
  );
}
